### ISSUE TITLE
Upgrade?

### ISSUE THREAD

**Issue by ghost** [looztra/fish-theme-yimmy-hg#1]
Hi @looztra  
I'm no longer maintaining omf, and would appreciate a ton if you can upgrade to [fisherman](https://github.com/fisherman/fisherman):
- Why? fisherman/fisherman#69 (comment)

Everything, including legacy plugins/themes work great with fisherman, but new content is _no_ longer compatible with oh-my-fish.

**Comment by looztra** [comment]
thanks @brj for the update.

I'm not using this theme anymore (and I think I was the unique user :D) so I think it's ok

**Comment by ghost** [comment]
Gotcha! See you around then and happing fishing :)
